Error: Invalid status code 503     at <anonymous> (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__f15ee0ad._.js?6:560:23)     at resolveErrorDev (https://6000-idx-studio-1746099697148.cluster-sumfw3zmzzhzkx4mpvz3ogth4y.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17512:48)     at processFullStringRow (https://6000-idx-studio-1746099697148.cluster-sumfw3zmzzhzkx4mpvz3ogth4y.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17728:23)     at processFullBinaryRow (https://6000-idx-studio-1746099697148.cluster-sumfw3zmzzhzkx4mpvz3ogth4y.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17716:9)     at progress (https://6000-idx-studio-1746099697148.cluster-sumfw3zmzzhzkx4mpvz3ogth4y.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17862:102)
errors in browser console: "server.ts:28  Server   Error: Route "/dashboard" used `cookies().get('sb-jcuwnzscskyusrraysut-auth-token')`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at Object.get (server.ts:28:30)
Object.get	@	server.ts:28

dashboard.tsx:393 Summarization successful:
Object
dashboard:1
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
intercept-console-error.ts:41 Error generating linkedin post: Error: Invalid status code 503
    at <anonymous> (generate-social-posts.ts:131:24)
error	@	intercept-console-error.ts:41
dashboard.tsx:463 Refunding 1 quota points due to errors.
use-websocket.ts:16 WebSocket connection to 'wss://6000-idx-studio-1746099697148.cluster-sumfw3zmzzhzkx4mpvz3ogth4y.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous)	@	use-websocket.ts:16"